Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,7 +17,7 @@ jobs:
       run: npm install -g @looker/look-at-me-sideways
     - name: Run LAMS
     #  See [PRIVACY.md](https://github.com/looker-open-source/look-at-me-sideways/blob/master/PRIVACY.md)
-      run: lams --reporting=save-no || echo "ERROR=true" >> $GITHUB_ENV
+      run: lams --reporting=yes || echo "ERROR=true" >> $GITHUB_ENV
     - name: Commit changes (e.g., issues.md)
       run: |
         git add .
